name: apis-canais-digitais
api-version: v1
description: Plugin para criar boilerplate code para consumir apis dos canais digitais 
display-name: apis-canais-digitais
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: Defina a stack alvo para o consumo da api
    type: text
    name: stack_alvo
    items:
      - Spring Open Feign   
      - Javascript geral   
  - label: Defina o caminho que você quer gerar os arquivos
    type: text
    name: caminho_geracao_arquivos
  - label: Qual o client id que deve ser usada nas requisições?
    type: text
    name: client_id

hooks:
  - type: render-templates
    trigger: after-render    
    path: templates-spring-open-feign
    working-dir: "{{project_name}}"
    condition:
      variable: stack_alvo
      operator: ==
      value: Spring Open Feign   
  - type: render-templates
    trigger: after-render    
    path: templates-javascript-geral
    working-dir: "{{project_name}}"
    condition:
      variable: stack_alvo
      operator: ==
      value: Javascript geral         
